version: '3.7'

services:
  BlobenSTAGING:
    image: 'bloben/app:staging'
    container_name: BlobenSTAGING
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    ports:
      - '127.0.0.1:8083:80'
    restart: always

  databaseBlobenSTAGING14:
    image: 'postgres:14.5-bullseye'
    container_name: databaseBlobenSTAGING14
    env_file:
      - .env
    volumes:
      - databaseBlobenDataSTAGING14:/var/lib/postgresql/data
    ports:
      - '8004:5432'
    restart: always

  redisBlobenSTAGING:
    image: redis:7.0.5-bullseye
    container_name: redisBlobenSTAGING
    volumes:
      - redisBlobenDataSTAGING:/data
    ports:
      - '6379'
    restart: always
#
#
volumes:
  databaseBlobenDataSTAGING14:
    name: databaseBlobenDataSTAGING14
  redisBlobenDataSTAGING:
    name: redisBlobenDataSTAGING
