version: '3.7'

services:
  BlobenDEV:
    image: 'bloben/app:development'
    container_name: BlobenDEV
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    ports:
      - '127.0.0.1:8082:80'
    restart: always

  databaseBlobenDEV14:
    image: 'postgres:14.6-bullseye'
    container_name: databaseBlobenDEV14
    env_file:
      - .env
    volumes:
      - databaseBlobenDataDEV14:/var/lib/postgresql/data
    ports:
      - '8003:5432'
    restart: always

  redisBlobenDEV:
    image: redis:7.0.5-bullseye
    container_name: redisBlobenDEV
    volumes:
      - redisBlobenDataDEV:/data
    ports:
      - '6379'
    restart: always
#
#
volumes:
  databaseBlobenDataDEV14:
    name: databaseBlobenDataDEV14
  redisBlobenDataDEV:
    name: redisBlobenDataDEV
